spring:
  profiles:
    active: dev

  application:
    name: ViReBackend

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  mvc:
    problemdetails:
      enabled: true

server:
  error:
    include-binding-errors: always

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:1h}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true

problem:
  base-uri: https://vire.dev/problems/

springdoc:
  swagger-ui:
    display-request-duration: true
    display-operation-id: true
