spring:
  profiles:
    active: dev

  application:
    name: ViReBackend

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  mvc:
    problemdetails:
      enabled: true

server:
  error:
    include-binding-errors: always

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:1h}

management:
  server:
    port: ${ACTUATOR_PORT:8081}
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

problem:
  base-uri: https://vire.dev/problems/

springdoc:
  swagger-ui:
    display-request-duration: true
    display-operation-id: true

info:
  app:
    name: ${spring.application.name}
    version: ${APP_VERSION:0.0.1-SNAPSHOT}
    description: ViRe backend service

logging:
  pattern:
    level: "%5p [traceId=%X{traceId:-},requestId=%X{requestId:-}]"
